on:
  pull_request:
    types: [opened, reopened]
  
jobs:
  pr-action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Post PR Comment
      uses: morgayle-ngt/docker-action-pr-giphy-comment@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        giphy-api-key: ${{ secrets.GIPHY_API_KEY }}

    - name: Post Javascript Action PR Comment
      uses: morgayle-ngt/js-action-pr-giphy-comment@0aa1966b1a31cfa0be64a78591ee6f01ac9c7f9d
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        giphy-api-key: ${{ secrets.GIPHY_API_KEY }}
# Dynamically obtain details from GitHub context with new index.js recompiled file
